# Generated by Django 2.0.5 on 2018-05-15 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=250, unique=True)),
                ('title', models.CharField(max_length=250)),
                ('asin', models.CharField(max_length=250, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=20)),
                ('review_count', models.IntegerField()),
                ('rating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('category', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('spam_rating', models.CharField(blank=True, max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=250, unique=True)),
                ('title', models.CharField(max_length=250)),
                ('rating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('date', models.DateField()),
                ('body', models.TextField()),
                ('author_username', models.CharField(max_length=250, unique=True)),
                ('author_url', models.CharField(max_length=250, unique=True)),
                ('verified_purchase', models.BooleanField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amazon.Item')),
            ],
        ),
    ]
