# Generated by Django 2.0.5 on 2018-05-16 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='author_url',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='review',
            name='author_username',
            field=models.CharField(max_length=250),
        ),
    ]
